# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fac82a2a55ce5d0f967c38a9cad10aaa2b5bbabeb21291eca9c2b2131b724e25ec51798fc07667f5311e235e2ede2554a311a624c19a345ef617177f153861a1

test:
  secret_key_base: 4862dc60c743f244c7805784f2828a94f4941b1149d04cc8f112559ab150b3e5d03f0901df64640aaa0d4b36ea9d3b2f1704bcb61fe20bc7a58bd4434dfde8a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
